### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by jollheef** [jollheef/appvm#21]
There are some command line (e.g. `--min-memory` and `--adj-memory` for autoballooning, also `--networking-model` in #20) switches that are better to have **also** in the configuration file that not introduced yet.

So the idea is to have a configuration file that will set all `Default("...")` in parameters for kingpin.

**Comment by msm-code** [comment]
:+1: I also thought about it. What do you think about per-VM configuration? For example some VMs are much more lightweight than the others (for example most terminal apps don't use minimal 1GiB ram)

**Comment by jollheef** [comment]
We can make it something like that (https://github.com/toml-lang/toml), using the name of the file for configuration for matching.

```toml
# https://github.com/toml-lang/toml
minimal_memory = 1024
adj_memory = 20

[[vm]]
# set configuration for ~/.config/appvm/nix/chromium.nix
name = "chromium" 
minimal_memory = 100500

[[vm]]
 # set configuration for ~/.config/appvm/nix/evince.nix
name = "evince"
offline = true
```

Looks easy and convenient.
